### ISSUE TITLE
Unable to install this using node js version v12.13.1

### ISSUE THREAD

**Issue by absk1s3** [Achronite/node-red-contrib-energenie-ener314rt#12]
Unfortunately, when I attempt to install this, it seems to fail every time.

I have latest version of raspian v10 buster (freshly installed), node-red v1.0.3 and node js version v12.13.1

I have pasted the log file on justpaste (link below)

https://justpaste.it/710ee

**Comment by Achronite** [comment]
This is a problem in the 'ref' library which is deprecated.  The new version (see develop branch) completely changes the dependencies.  I'll take this as a prompt to get it released :)
