### ISSUE TITLE
Not an issue, but a question please.

### ISSUE THREAD

**Issue by pmh1947** [Achronite/node-red-contrib-energenie-ener314rt#56]
Have you done any work on a node-red module for controlling Energenie products vis the proprietary web based interface. The reason I  ask is that I have some legacy Energenie devices that I would like to integrate into my home node-red network, that is now predominately Tasmota/Sonoff based but with some EweLink devices.  Otherwise, do you want some cheap Energenie  power sockets , RF remotes, and 2 light switches :)

**Comment by Achronite** [comment]
When you say 'Proprietary web based interface' do you mean the MiHome App?  That needs the MiHome gateway, and this module does not use that, it uses the ENER314-RT add-on board for the Raspberry Pi to send the radio signals (instead of the RF remote).  You can pick one up relatively cheaply (e.g £13.60 on Amazon UK at the mo). You can then directly control the sockets/switches using the Control node directly from the Raspberry Pi.

**Comment by pmh1947** [comment]
Sorry, my sloppy wording.   I meant the MiHome App, but could not remember the correct name.  I already have the  MiHome Gateway, and I understand that your module does not support that. Hence my question.

Sent from Mail for Windows

**Comment by Achronite** [comment]
No it does not use the MiHome web interface, I don't even own a MiHome gateway!

**Comment by pmh1947** [comment]
I may buy a Pi adaptor - cheap enough- but my software skills are limited and the reviews for that module are less than enthusiastic! It appears that you presumably have to  run code on the the Pi to configure the interface before using your node?

**Comment by Achronite** [comment]
These are modules for [Node-Red](https://nodered.org/). you shouldn't need to code, just use the drag and drop and configure the switches.  I've done all the hard work for you :).  
![image](https://user-images.githubusercontent.com/10363609/172141032-5111eb07-e0f9-4da7-a7f8-f446e1509deb.png)
Example code (copy and paste this in to node-red).

`[{"id":"270716ba749fe760","type":"inject","z":"d653cc8e.584b48","name":"On","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":270,"y":840,"wires":[["c4ffd1d61b494947"]]},{"id":"108fd3eb6ce4e64f","type":"inject","z":"d653cc8e.584b48","name":"Off","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":270,"y":900,"wires":[["c4ffd1d61b494947"]]},{"id":"c4ffd1d61b494947","type":"ook-switch","z":"d653cc8e.584b48","name":"Control","zone":"1","switchNum":"3","board":"14a2599b.c98c8e","x":460,"y":880,"wires":[[]]},{"id":"14a2599b.c98c8e","type":"energenie-board","name":"ENER314-RT","timeout":"5000"}]`

**Comment by pmh1947** [comment]
OK thanks for your help. Ordered from Amazon.
