### ISSUE TITLE
MIHO010 doesn't dim

### ISSUE THREAD

**Issue by GeoffNT** [Achronite/node-red-contrib-energenie-ener314rt#59]
I'm new to Energenie and these nodes and have just set up a very basic system with the ENER314_RT board and a MIHO010 dimmer. 

On and Off works OK, but I can't get dim to work.

I've tried payload as 4 and 40 (numbers not strings) payload.brightness as the same but the lamps stays at full brightness regardless. The dimmer node itself updates with the correct brightness underneath but the bulb brightness does not adjust. I'm using an old 60W incandescent bulb for testing.

**Comment by Achronite** [comment]
Can you please help by showing the node-red-log for when you change the brightness levels?  There should be some lines with ${zone}:${switchNum} state=${switchState} xmits=${xmits} in it.  The switchNum and state should change as the brightness does.

**Comment by GeoffNT** [comment]
This is a summary of the commands I send, the node-red-log and the actual result:

            Command	                                                      Log	                                                           Result
msg.payload : Object on: true		[info] [ook-dimmer:Dimmer] 2:1 state=true xmits=20	Bulb turns on at 100%
		
msg.payload : Object brightness: 4		[info] [ook-dimmer:Dimmer] 2:4 state=true xmits=20	Bulb stays on at 100%
	
msg.payload : Object object brightness: 7	[info] [ook-dimmer:Dimmer] 2:4 state=false xmits=20	Bulb stays on at 100%

Interesting that when I send the brightness 7 (for 100%) command the state changes to false and the level stays at 4 but the bulb stays on

**Comment by Achronite** [comment]
> Interesting that when I send the brightness 7 (for 100%) command the state changes to false and the level stays at 4 but the bulb stays on

That is expected behaviour according to the code i reused, it supposedly uses the switchNum & true/false combination to inform of the brightness level as follows:
```
'0': Channel 1 false: Turn dimmer Off
'1': Channel 1 true: Turn dimmer On at last light level set
'2': Channel 2 true: Set dimmer to 20% (turn on at 20% if off)
'3': Channel 3 true: Set dimmer to 30% (turn on at 30% if off)
'4': Channel 4 true: Set dimmer to 40% (turn on at 40% if off)
'5': Channel 2 false: Set dimmer to 60% (turn on at 60% if off)
'6': Channel 3 false: Set dimmer to 80% (turn on at 80% if off)
'7': Channel 4 false: Set dimmer to 100% (turn on at 100% if off)
```
It looks like it *should* be working as intended then, maybe the bulb is not dimmable or something?  The only other thing I saw different in the pyenergenie code was that times the transmission is sent was set to 75 (my default is 20).  Can you try that by sending an 'advanced' payload to the node? e.g.
```
{
            "brightness": 80,
            "repeat": 75
 }
```

**Comment by GeoffNT** [comment]
I think I have a faulty dimmer switch. I've only just learned that the remote can set various dim levels also (As per picture below from their technical dept)  

My dimmer doesn't dim using any of those button presses either. I'm using a 60W incandescent bulb so should be no problem with dimming that. I can only presume the switch is faulty so will return it. Thanks for your quick responses.

![image](https://user-images.githubusercontent.com/62440007/189409426-ecb6ca50-a58a-4130-9609-db7c974e4335.png)
