### ISSUE TITLE
Can these nodes detect button presses on a remote?

### ISSUE THREAD

**Issue by GeoffNT** [Achronite/node-red-contrib-energenie-ener314rt#60]
Sorry this is a newbie question not an issue but I don't know where else to ask. 

Can these nodes and a ENER314-RT monitor/detect a button press from the ENER002-G remotes? 

It would be useful if these button presses could be monitored and then used for other things either together with their device pairing or as a complete standalone remote. 

I have searched around for the answer to this but couldn't find anything.

**Comment by Achronite** [comment]
No they can't detect button presses at the moment.  I did think of adding it though (see #2), but decided against it for now as each device can learn 2 different controller codes; so it is possible to have the remote and these nodes working at the same time.

**Comment by GeoffNT** [comment]
Fair enough. 

I was just thinking of using the remote (without it being paired to any device) as a cheap and cheerful 10 button remote for controlling anything I want within Node Red.
