### ISSUE TITLE
Control/OOK Receive 0 (all in zone) strange behaviour

### ISSUE THREAD

**Issue by GeoffNT** [Achronite/node-red-contrib-energenie-ener314rt#61]
Sorry, me again ;-(

I am testing a set of 4 of the basic sockets type ENER002. I have paired them OK as Zone 2 switches 1,2,3,4. The 4 control nodes work them all correctly individually. 

I have also set up a control node for "all on" or "all off" using Zone 2, switch number 0. Within the control node it works fine when I hit the "mortar board" and "power" buttons, all turn on or off fine. But if I then send a payload of true or false to the same node only switch 1 turns on or off. I have also tried sending a payload with payload.switchNum set to 0 and payload.on set to true of false but this also just switches switch number 1.

Another strange thing is that in trying to debug this I ran node-red-log in a PuTTY session but am now getting no [info] level output when these nodes operate other than these below initially. I was getting log info the other day OK, what could I have done to turn it off?!! 

[info] [energenie-board:ENER314-RT] ener314rt: radio initialised
{info] [energenie-board:ENER314-RT] starting monitor thread, timeout=5000

**Comment by Achronite** [comment]
Hmm... strange.  I'll do some investigation.

The debug line you probably saw was from the dimmer node, which still has one log statement in it.  It is beta and untested by me (I don't have a dimmer). 

You could uncomment the log line at line 57 in red/ook-switch.js if you want that outputting too.... or just wait for me to investigate further.

**Comment by GeoffNT** [comment]
I've uncommented the line you suggested and when I sent an all units command (Zone 2 Switch number 0) I get:

 [ook-switch:Test All in Zone command] 2:1 state=true xmits=20

and only switch number 1 operates.

**Comment by Achronite** [comment]
This was a bug, I think I introduced it when I added some error checking code AGES ago.

I have now fixed it on the develop branch.  Unfortunately I need to do some more testing of the rest of the changes that have been made in this branch before I can release it to everyone.  This should be early next week as v0.5.1

**Comment by Achronite** [comment]
v0.5.1 Released.

**Comment by GeoffNT** [comment]
Updated to 0.5.1 and working great. 

Thanks very much for all of your work on these nodes.
