### ISSUE TITLE
Testing of MiHome Thermostat (MIHO069)

### ISSUE THREAD

**Issue by sgulati-hub** [Achronite/node-red-contrib-energenie-ener314rt#63]
I could not manage to send any commands to Thermostat however successfully received messages from Thermostat. I have tried commands like following: 
Setting temperature : { "command": 244, "data": 17 }
Identify : { "command": **191}

Also, noticed that Thermostat sends the TARGET_TEMP only when target temperature changes (either due to schedule on the MiHome Web/App or Manual change via Web/App). Is there any way to get the target temperature when needed? It seems mihome hub can wake up and send the commands to the Thermostat whenever needed.

**Comment by Achronite** [comment]
Unfortunately I don't own a Thermostat, so I'm not sure what commands it responds to, the ones on the manual page are based on what works with the radiator valves and are untested on the Thermostat.

You could try the 'REQUEST_DIAGNOSTICS' (166) command to see if it reports the TARGET_TEMP.  Please let me know what it returns.

It is interesting that the MiHome hub seems able to send commands at any time. It currently waits until a WAKEUP message is received and sends the last 'cached' command. It wouldn't be too difficult to change that behaviour though.

The main issue we have with the Thermostat is working out exactly what commands it responds to!  If you manage to get it to work with any commands please let me know.

**Comment by Achronite** [comment]
It might be better if we continue this discussion on the the original issue for Thermostat #36.  I'll reopen it.
