### ISSUE TITLE
Queued commands for MIHO013 eTRV

### ISSUE THREAD

**Issue by genestealer** [Achronite/node-red-contrib-energenie-ener314rt#64]
I cannot seem to queue commands for MIHO013 eTRV, I have tried having two instances of the same node, but I see this is a limitation.

Can I check this is correct?

![image](https://user-images.githubusercontent.com/5207490/211088052-ff08c658-edb3-4389-a448-123daee71dfe.png)

![image](https://user-images.githubusercontent.com/5207490/211088205-08154725-ac7e-49c1-8d7f-cfaa7c762a6e.png)

**Comment by Achronite** [comment]
It was working last time I tried.  Can you please show me the command you are passing in to the eTRV node?

Co-incidentally, I've just started on producing an MQTT version for Home Assistant.  I don't have the eTRV commands working yet though.  See https://github.com/Achronite/mqtt-energenie-ener314rt

**Comment by Achronite** [comment]
@genestealer Just had a thought - Did you mean queueing/caching more than 1 command per eTRV?

**Comment by genestealer** [comment]
Closed, as I see there a limit of queueing/caching of only 1 command per eTRV.
