### ISSUE TITLE
Issue in: node-red-contrib-energenie-ener314rt FAQ

### ISSUE THREAD

**Issue by genestealer** [Achronite/node-red-contrib-energenie-ener314rt#68]
Step "Recompile energenie-ener314rt by: node-gyp configure build."
Missing dependency step to install node-gyp "sudo npm install -g node-gyp"
![image](https://user-images.githubusercontent.com/5207490/211321451-110f6148-5d10-4a29-8df5-2c46cc235e9a.png)

![image](https://user-images.githubusercontent.com/5207490/211321341-09eef0c9-4ba7-41b6-acfb-ebe79dd816dc.png)

After installing:
![image](https://user-images.githubusercontent.com/5207490/211321536-4c5f73c7-5a00-4112-96bd-4a5044f5474d.png)

**Comment by Achronite** [comment]
OK I'll add the missing step.
