### ISSUE TITLE
Migrate C calls to use node.js N-API instead of ffi

### ISSUE THREAD

**Issue by Achronite** [Achronite/node-red-contrib-energenie-ener314rt#7]

**Comment by Achronite** [comment]
Initial N-API version now working in v0.3.0, but still to do async calls to avoid blocking node.js main thread

**Comment by pcorner** [comment]
Have you considered teh c++ addon-api  ?
https://github.com/nodejs/node-addon-examples
I think it would be worth considering, as you get all the treadsafe and async functionality that you are looking for and have as native code

**Comment by Achronite** [comment]
@pcorner all the code is in C, and as the C++ addons is a wrapper for N-API, not sure I would get that much benefit from it.

Anyway I've got 1 of the async calls working now (admittedly it was a little tricky to work out, there are not many examples out there!) I just need time to code the rest now.
