### ISSUE TITLE
Duplicate Openthings Listing

### ISSUE THREAD

**Issue by genestealer** [Achronite/node-red-contrib-energenie-ener314rt#70]
I'm seeing a duplicate Openthings listing, which is persistent after reboot. 
Would you know how to remove it, as it pops up a warning on each Deployment. 
![image](https://user-images.githubusercontent.com/5207490/222545591-f278b975-ac2b-4de3-9e6c-319714710714.png)

**Comment by Achronite** [comment]
Try right clicking on the config item with 0 uses and deleting it.On 2 Mar 2023 20:35, R Huish ***@***.***> wrote:
I'm seeing a duplicate Openthings listing, which is persistent after reboot.
Would you know how to remove it, as it pops up a warning on each Deployment.

**Comment by Achronite** [comment]
Open the config item with 0 uses by double clicking on it and choose 'delete' (top left), then redeploy.

**Comment by genestealer** [comment]
Fixed, thank you
