### ISSUE TITLE
Support for ENER314?

### ISSUE THREAD

**Issue by daxliniere** [Achronite/node-red-contrib-energenie-ener314rt#71]
Hey @Achronite,
Thank you for providing this package to the community. What was the difficulty you had in implementing ENER314 support?
From what I can see, it just needs its data pins (D0-D3) to be set to form a 4-bit binary code and there's a table of permissible codes in the documentation.

All the best,
Dax.

**Comment by Achronite** [comment]
Yeah - it is quite easy from what I remember for the 'old' board.  I did it using the built-in node-red GPIO 'nodes' at the time.  You are just limited to 6 devices (not 4 as energenie claims) in total with the binary combinations.

**Comment by daxliniere** [comment]
Yes, I'm staring down the barrel of that now. Trying to work out a better way to send the 4-bits than 4 pairs of high/low Inject nodes. 😬
